include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_single_quotes: true
    prefer_interpolation_to_compose_strings: false
    avoid_print: false
    use_build_context_synchronously: false
    depend_on_referenced_packages: false
    avoid_dynamic_calls: false
    constant_identifier_names: false
    non_constant_identifier_names: false
    no_wildcard_variable_uses: false
    
analyzer:
  errors:
    deprecated_member_use: ignore
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - test/
    - widget_catalog/
    - maintainance/**
    - pubspec.yaml
  
