include: package:lint/analysis_options.yaml

linter:
  rules:
    file_names: false
    curly_braces_in_flow_control_structures: false
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_single_quotes: true
    avoid_void_async: false
    sized_box_for_whitespace: false
    prefer_interpolation_to_compose_strings: false
    avoid_print: false
    avoid_positional_boolean_parameters: false
    use_string_buffers: false
    use_build_context_synchronously: false
    depend_on_referenced_packages: false
    join_return_with_assignment: false
    unnecessary_string_escapes: false
    avoid_dynamic_calls: false
    constant_identifier_names: false
    non_constant_identifier_names: false
    no_wildcard_variable_uses: false
    


analyzer:
  errors:
    deprecated_member_use: ignore
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - test/
    - widget_catalog/
    - maintainance/**
    - pubspec.yaml
  
